package eu.learnpad.simulator.monitoring.impl;

public enum RuleTemplateEnum {
	EVENTAAFTEREVENTB,EVENTABETWEENEVENTB,INFRASTRUCTUREVIOLATION,NOEVENTFROMINFRASTRUCTURE,CHECKSERVICESLAFAILURE3TIMES_FIRSTPART, CHECKSERVICESLAFAILURE3TIMES_SECONDPART
}



