package eu.learnpad.monitoring.glimpse.impl;

public enum RuleTemplateEnum {
	EVENTAAFTEREVENTB,EVENTABETWEENEVENTB,INFRASTRUCTUREVIOLATION,NOEVENTFROMINFRASTRUCTURE,CHECKSERVICESLAFAILURE3TIMES_FIRSTPART, CHECKSERVICESLAFAILURE3TIMES_SECONDPART
}



